# Generated by Django 4.1 on 2022-08-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('IsSuperUser', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
            ],
        ),
    ]
