# Generated by Django 4.1 on 2022-08-10 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetailsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
