# Generated by Django 4.1 on 2022-08-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdetailsapp', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=200)),
                ('UserName', models.CharField(max_length=200)),
                ('IsSuperUser', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
