# Generated by Django 4.1 on 2022-08-13 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetailsapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='userName',
        ),
    ]
