# Generated by Django 4.1 on 2022-08-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_rename_approval_status_task_approvalstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ApprovalStatus',
        ),
        migrations.RemoveField(
            model_name='task',
            name='AssignedManager',
        ),
        migrations.RemoveField(
            model_name='task',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='StartTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Status',
        ),
    ]
