# Generated by Django 4.1 on 2022-08-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_remove_task_approvalstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='Description',
        ),
    ]
