# Generated by Django 4.1 on 2022-08-09 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_task_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
