# Generated by Django 4.1 on 2022-08-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0006_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('TaskName', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=100)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('CreatedDate', models.DateField()),
                ('ApprovalStatus', models.CharField(max_length=100)),
                ('AssignedManager', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
