# Generated by Django 4.1 on 2022-08-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='EndTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='StartTime',
            field=models.DateField(),
        ),
    ]
