# Generated by Django 4.1 on 2022-08-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_task_endtime_alter_task_starttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='ApprovalStatus',
        ),
        migrations.RemoveField(
            model_name='task',
            name='AssignedManager',
        ),
        migrations.RemoveField(
            model_name='task',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='task',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='StartTime',
        ),
    ]
