# Generated by Django 4.1 on 2022-08-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_remove_task_approvalstatus_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
