# Generated by Django 4.1 on 2022-08-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_remove_task_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='EndTime',
        ),
        migrations.RemoveField(
            model_name='task',
            name='StartTime',
        ),
    ]
