# Generated by Django 4.1 on 2022-08-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_task_endtime_remove_task_starttime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
